repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            stages: [commit]

          - id: check-yaml
            stages: [commit]

          - id: debug-statements
            stages: [commit]

          - id: name-tests-test
            stages: [commit]
            args: [--pytest-test-first]

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            stages: [commit]
            args: ["--line-length=120"]

    - repo: https://github.com/hhatto/autopep8
      rev: v2.0.4
      hooks:
          - id: autopep8
            stages: [commit]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: ["--ignore=F403,F405,F401,E501,W503"]
            stages: [commit]

    - repo: local
      hooks:
          - id: validate-commit-msg
            name: validate-commit-msg
            entry: ./commit-msg.sh
            language: script
            stages: [commit-msg]
